name: Send Discord Message

on:
  schedule:
    - cron: '30 0 * * *'

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests  # Install requests library

      - name: Run the script
        run: |
          python send_message_script.py  # Execute the script
